### PR TITLE
Add additional organization actions

### PR DESCRIPTION
**Pull request by dylanmtaylor**
We believe that these actions are needed to get the account details including the tag (name) for each. This requires an appropriate organization policy in the management account to work correctly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by js37** [comment]
I'll review and follow up.

**Comment by dylanmtaylor** [comment]
> I'll review and follow up.

Thanks. I'll use this in our org in the meantime :)

**Comment by js37** [comment]
Can you share the specific problem you were having that you believed you needed to add these permissions?

`- organizations:ListAccounts` on `ProwlerCodeBuildRole` is so that the CodeBuild job can make this call in the BuildSpec:

`account_list=$(aws organizations list-accounts --query 'Accounts[?Status==`ACTIVE`].Id' --output text)` 

After that, Prowler uses the `ProwlerIntegrationCodeBuildRole` to do the Prowler checks. That has SecurityAudit policy which grants `"organizations:Describe*" and "organizations:List*"`

**Comment by dylanmtaylor** [comment]
We were having issues with it not reading in the labels of accounts. In particular, we wanted prowler to get account name, etc from AWS Organization management account ("root account"). 

Reference: https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/aws/organizations/

"Make sure the role in your AWS Organizations management account has the permissions organizations:DescribeAccount and organizations:ListTagsForResource."

**Comment by js37** [comment]
Okay, I will try and reproduce next week. I expected that to be done with the other role that has the permission already.

**Review by bulebuk — APPROVED** [review]

**Review by bstucker — APPROVED** [review]
Approved, recommend subsequent update to add section in read-me to explain roles needed while executing prowler.

**Comment by js37** [comment]
This is the correct fix because we don't pass the -o and specify an organizational role. You are correct, I was mistaken how this info is added to the Prowler report. 

I'll follow up with an update to the documentation. You will also need to update the resource policy if you are not using a delegated admin.

**Comment by dylanmtaylor** [comment]
> This is the correct fix because we don't pass the -o and specify an organizational role. You are correct, I was mistaken how this info is added to the Prowler report. 
> 
> I'll follow up with an update to the documentation. You will also need to update the resource policy if you are not using a delegated admin.

We do actually delegate admin - probably worth documenting that though, as it may be non-obvious at first.

**Pull request merged**
